<head>
    <title>Edit Thread</title>
    <style>
        .container1{
            max-width: 800px;
         
        }
    </style>
</head>

<div id="view-content">
    <div class="container1">
           <div class="jumbotron col-sm-1-offset-1 "style="margin-top: 50px;  width: 500px;  margin-left: 50px; background-color:rgba(102,102,255,0.4);"> 
    <?php
	echo $this->form;
        ?>
    </div>
</div>
</div>