<head>  
    
<title>Home</title>
</head>
    <style>

            .fontSize
            {
                font-family: fantasy;
                font-size: 40px;
            }
    </style>    
    <div style="height:100px ;display:block;"> </div>
       <?php
       for($j = 0; $j<count($this->categories); $j++){ ?>
<table  style="width:1000px; margin: 0 auto;"class="table table-hover">
    <tr>
       
        <td  class="danger" width='170px' height='80px'>
            <img style="margin-left: 180px;" src="../category_images/<?php echo $this->categories[$j]['image'];?>" class="img-rounded"  width="110" height="60px"/>
            
        </td>
        
        <td  class="danger" >
            <a style="margin-left: 90px; margin-top: 5px;" class="fontSize" href="<?php echo $this->baseUrl()?>/forums/list/id/<?php echo $this->categories[$j]['id'];?>" > <?php echo $this->categories[$j]["name"];?> </a>
            
        </td>
        
     <?php if($this->admin==1) {?>  
 <td class="danger" width='150px'>    
<a style="margin-left: 25px; margin-top: 5px; width: 80px;" href="<?php echo $this->baseUrl()?>/categories/edit/id/<?php echo $this->categories[$j]['id'];?>/e/-1" class="btn btn-success btn-lg" > Edit </a>

</td>

        <td class="danger" width='150px' >    
<a style="margin-left: 25px; margin-top: 5px;" href="<?php echo $this->baseUrl()?>/categories/delete/id/<?php echo $this->categories[$j]['id'];?>/catImg/<?php echo $this->categories[$j]['image'];?>/d/-1" class="btn btn-danger btn-lg" > Delete </a>

</td>
<?php }?>

    </tr>
    </table>
<div class="jumbotron col-sm-1-offset-1 "style="  width: 900px;  margin :0 auto ; padding: 10px 10px 10px 10px; background-color:rgba(102,102,255,0.4);">
 <table style=" margin-bottom:0px;" class="table table-hover">  
        <?php
    
for($i = 0; $i<count($this->forums); $i++){
    if($this->forums[$i]['cat_id'] == $this->categories[$j]['id']) {
?>


    <tr>
        <td  class="info" width="180px" height="70px">
            <img width="150px" height="50px" src="../forum_images/<?php echo $this->forums[$i]['image'];?>" class="img-rounded"/>
            
        </td>
    <td class="info">
<a style="margin-left: 25px; margin-top: 5px; font-size: 30px;" href="<?php echo $this->baseUrl()?>/threads/list/id/<?php echo $this->forums[$i]['id'];?>" class="text-danger"> <?php echo $this->forums[$i]["name"];?></a>
    </td>
 
<?php if($this->admin==1) {?> 
    
               <td class="active" width='150px' >    
<a style="margin-left: 25px; margin-top: 5px; width: 80px; " href="<?php echo $this->baseUrl()?>/categories/lockforum/id/<?php echo $this->forums[$i]['id'];?>/lock/<?php echo $this->forums[$i]['is_locked'];?>" class="btn btn-warning btn-lg" > <?php if( $this->forums[$i]['is_locked'] == 0) echo "Lock"; else{ echo "Unlock";}?> </a>

</td>
 <td class="success" width='150px'>    
<a style="margin-left: 25px; margin-top: 5px; width: 80px;" href="<?php echo $this->baseUrl()?>/forums/edit/id/<?php echo $this->forums[$i]['id'];?>/catgId/<?php echo $this->forums[$i]['cat_id']?>/c/1 " class="btn btn-success btn-lg" > Edit </a>

</td>

        <td class="warning" width='150px' >    
<a style="margin-left: 25px; margin-top: 5px;" href="<?php echo $this->baseUrl()?>/forums/delete/id/<?php echo $this->forums[$i]['id'];?>/img/<?php echo $this->forums[$i]['image'];?>/catgId/<?php echo $this->forums[$i]['cat_id']?>/c/1" class="btn btn-danger btn-lg" > Delete </a>

</td>


<?php }?>
    </tr>
<?php

}}
      echo '</table> </div> <br> <br> <br>';
}
?>

