<html>
    <head>
        <?php echo $this->headLink()->appendStylesheet($this->baseUrl('/css/bootstrap.css')); ?> 
        <?php echo $this->headLink()->appendStylesheet($this->baseUrl('/css/bootstrap-theme.css')); ?> 
        <?php echo $this->headScript()->prependFile($this->baseUrl('/js/jquery-2.1.3.min.js')) ?> 
        <?php echo $this->headScript()->prependFile($this->baseUrl('/js/bootstrap.js')) ?>
        
        
    </head>
    
    </head>
 <header>
        <style>
            

            .container{
                
                background: url("<?php echo $this->baseUrl(); ?>/3.jpg") no-repeat center center fixed;
                background-repeat: no-repeat;    
                min-height: 790px;                
                background-size: 100% 100%;

            }
            
            #user{
            width : 200px ;
            height: 100px;
            float: right;
            
        }
        #profile_img{
            width : 100px;
            height: 100px;
            border-style: solid;
            border-width: 1px;
            float: left;
        }
        #menu{
            width: 900px;
            float: left;
        }
        #content{
            display: block;
        }
        #name{
            float: left;
            margin-top: 20px;
            margin-right: 5px;
            font-size: 20px;
            font-family: "Times New Roman", Times, serif;
            font-style: oblique;
        }
        #name a{
            color : black;
        }
       #name a:hover {
            color: #ffffff;
        }
          
            
           
        </style>

    </header>
<body>
   <div class="container"> 

        <?php
        $user_id = -1;
        $is_admin = 0;
        $authorization = Zend_Auth::getInstance();
        if ($authorization->hasIdentity()) {
            $storage = $authorization->getStorage();
            $user_id = $storage->read()->id;
            $user_model = new Application_Model_Users();
            $user = $user_model->getUserById($user_id);
            $is_admin = $user[0]["is_admin"];
        }
        $state_model = new Application_Model_SystemStatus();
        $sys_state = $state_model->getSystemState();
        ?>
        <div id="menu">
            <nav class="navbar navbar-inverse">
                <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                    <ul class="nav navbar-nav">
                        <li><a href="<?php echo $this->baseUrl(); ?>/categories/main">Home <span class="sr-only">(current)</span></a></li>
                        <?php
                        if ($user_id == -1) {
                            ?>
                            <li><a href="<?php echo $this->baseUrl(); ?>/users/login">Login</a></li>
                            <li><a href="<?php echo $this->baseUrl(); ?>/users/register">Register</a></li>
                            <?php
                        } else {
                            ?>
                            <li><a href="<?php echo $this->baseUrl(); ?>/users/profile">Profile</a></li>
                            <li><a href="<?php echo $this->baseUrl(); ?>/users/list">All Users</a></li>
                            
                            <?php
                        }
                        if ($is_admin == 1) {
                            ?>
                            <li><a href="<?php echo $this->baseUrl(); ?>/categories/add">Add Category</a></li>
                            <li><a href="<?php echo $this->baseUrl(); ?>/forums/add">Add Forum</a></li>
                            <li><a href="<?php echo $this->baseUrl(); ?>/users/adduser">Add User</a></li>
                            <li><a href="<?php echo $this->baseUrl(); ?>/categories/list">All Categories</a></li>
                            <?php
                            if ($sys_state == 0) {
                                ?>
                                <li><a id="state" href ='javascript:;' onclick='switchSys()' >Close System</a></li>
                                <?php
                            } else {
                                ?>
                                <li><a id="state" href ='javascript:;' onclick='switchSys()'>Open System</a></li>
                                <?php
                            }
                        }
                        ?>
                    </ul>
                </div>
            </nav>
        </div>

        <?php
        if ($user_id != -1) {
            echo "<div id='user'>";
            $user_model = new Application_Model_Users();
            $user = $user_model->getUserById($user_id)[0];
            echo "<div id='name'><a href='" .$this->baseUrl()."/users/userprofile/id/{$user['id']}'><b>" . $user['name'] . "</b></a><br/><a href='". $this->baseUrl()."/users/logout'><b>Logout</b></a></div>";
            ?>
            <img class="img-rounded" id="profile_img" src="<?php echo $this->baseUrl(); ?>/profile_images/<?php echo $user['image']; ?>"></img>
            <?php
            echo "</div>";
        }
        ?>


        <div id="content">
            <br><br><br>
            <?php echo $this->layout()->content; ?> 
        </div>
    </div>
    <script>

        function switchSys() {
            $.ajax({
                dataType: "json",
                url: "<?php echo $this->baseUrl() . '/system-status/switch' ?>",
                data: [],
                success: function (data) {
                    if (data.info == 1) {
                        $("#state").text("Open System");
                    } else {
                        $("#state").text("Close System");
                    }
                }
            });
        }

    </script>
<body>
<html>