<head>
<title>Add User</title>
</head>
<div id="view-content">
    
    <div class="jumbotron col-sm-1-offset-1 "style="margin-top: 30px;  width: 400px; height: 650px;  margin-left: 100px; background-color:rgba(102,102,255,0.4);">
            

    <?php
    if (isset($this->errorMessage)) {

        echo $this->errorMessage;
    }
    ?>
        
    <?php echo $this->adduser;
 

?>

    </div>
</div>


