<head>
<title> Successfully Registered</title>
</head>
<style>
        h2 {
            color:brown;
        }

        
    </style>
<div id="view-content">
	<div class="jumbotron col-sm-1-offset-1 "style="margin-top: 150px;  width: 550px;  margin-left: 50px; background-color:rgba(102,102,255,0.4);"> 
        <h2>Thank you! Your Registration Has Been Confirmed.</h2>
        </div>
    <a style="font-size: 30px; font-family: fantasy; margin-left: 100px;"href='<?php $i=$this->baseUrl()."/users/login"; echo $i; ?>'> Click here to login</a>
</div>