<html>
    <header>
       
<title>Login</title>

        <style>
            .jumbotron
            {
                width: 400px;
                margin-left: 50px;
                margin-top: 50px;
                background-color:rgba(102,102,255,0.4);
            }
            #but{
                margin-left: 190px; 
                border-top-width: 4px; 
               
            }


        </style>

    </header>
    <body>
        <div class="col-lg-12"> 
            <!--            <div class="container">-->


            <div class="header">
                <div class="jumbotron">

                    <h1 class="col-md-offset-3"  style="color: white"> &nbsp; Sky
                        <br>
                        <small class="col-md-offset-1 "style="color: white; margin-left: 40px;" > &nbsp;  &nbsp; login</small></h1>

                    <div class="form-group-lg"></div>

                    <form  method="post" action="" class="form-horizontal">
                        <div class="form-group">

                        </div>
                        <div class="form-group">
                            <div class="col-sm-10">
                                <?php
                                if (isset($this->errorMessage)) {

                                    echo $this->errorMessage;
                                }
                                ?>
                                <?php
                                echo $this->login;
                                ?> 
                                
                                <a  id="but" href="<?php echo $this->baseUrl(); ?>/users/register" class="btn btn-primary ">Sign Up</a>
                            </div>
                        </div>



                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
</body>
</html>