<head>
    <title>Error</title>
    <style>
        h2 {
            color:brown;
        }
    </style>
</head>
<div class="jumbotron col-sm-1-offset-1 "style="margin-top: 200px;  width: 500px;  margin-left:40px; background-color:rgba(102,102,255,0.3);">
    <h2><?php echo $this->systemoff;?></h2>
</div>
   
<body>
    <script>
        $("#menu").remove();
        $("#user").remove();
        $("#name").remove();
        $("#profile_img").remove();
        
        
        </script>
</body>
